services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: registered
      MYSQL_USER: ankush
      MYSQL_PASSWORD: ankush
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: ./app # Path to your PHP application's Dockerfile
    container_name: php_app
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_DATABASE: registered
      MYSQL_USER: ankush
      MYSQL_PASSWORD: ankush
    volumes:
      - ./app:/var/www/html

volumes:
  mysql_data:
