services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user_name
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: ./app # Path to your PHP application's Dockerfile
    container_name: php_app
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user_name
      MYSQL_PASSWORD: your_password
    volumes:
      - ./app:/var/www/html

volumes:
  mysql_data:
